Map: 100%|████████████████████████████████████████████████████████████████████████| 4358/4358 [00:00<00:00, 5454.05 examples/s]
Map: 100%|██████████████████████████████████████████████████████████████████████| 36718/36718 [00:07<00:00, 5155.92 examples/s]
Map: 100%|████████████████████████████████████████████████████████████████████████| 3760/3760 [00:00<00:00, 5716.31 examples/s]
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]
/home/ubuntu/.local/lib/python3.10/site-packages/pytorch_lightning/utilities/model_summary/model_summary.py:231: Precision bf16-mixed is not supported by the model summary.  Estimated model size in MB will not be accurate. Using 32 bits instead.

  | Name  | Type            | Params | Mode
-------------------------------------------------
0 | model | GPT2LMHeadModel | 124 M  | eval
-------------------------------------------------
124 M     Trainable params
0         Non-trainable params
124 M     Total params
497.759   Total estimated model params size (MB)
0         Modules in train mode
164       Modules in eval mode
/home/ubuntu/.local/lib/python3.10/site-packages/pytorch_lightning/loops/fit_loop.py:527: Found 164 module(s) in eval mode at the start of training. This may lead to unexpected behavior during training. If this is intentional, you can ignore this warning.
Epoch 0:   4%|█▋                                         | 181/4589 [00:32<13:18,  5.52it/s, v_num=btkb, train_loss_step=0.300]
`loss_type=None` was set in the config but it is unrecognised.Using the default loss: `ForCausalLMLoss`.

Detected KeyboardInterrupt, attempting graceful shutdown ...
Exception ignored in atexit callback: <function _start_and_connect_service.<locals>.teardown_atexit at 0x70a6968a15a0>
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.10/site-packages/wandb/sdk/lib/service_connection.py", line 94, in teardown_atexit
    conn.teardown(hooks.exit_code)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/wandb/sdk/lib/service_connection.py", line 226, in teardown
    self._router.join()
  File "/home/ubuntu/.local/lib/python3.10/site-packages/wandb/sdk/interface/router.py", line 75, in join
    self._thread.join()
  File "/usr/lib/python3.10/threading.py", line 1096, in join
    self._wait_for_tstate_lock()
  File "/usr/lib/python3.10/threading.py", line 1116, in _wait_for_tstate_lock
    if lock.acquire(block, timeout):
KeyboardInterrupt:
